#!/bin/bash

SELF=`basename $0`
SERVICE=$1
if [ -z "$1" ]
then
    cat <<EOF
usage: ${SELF} service
EOF
    exit
fi


for pid in `ps ax | grep ${SERVICE}| grep -v ${SELF}| grep -v grep |awk '{print $1}'`
do
    sudo cat /proc/${pid}/limits | grep 'Max open files'
done   

