#!/bin/bash

if [ $# != 1 ]
then
    echo "usage: ${SELF} service"
    exit;
fi


SELF=`basename $0`
SERVICE=$1


for pid in `ps ax | grep ${SERVICE}| grep -v ${SELF}| grep -v grep |awk '{print $1}'`
do
    sudo cat /proc/${pid}/limits | grep 'Max open files'
done   

